# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 01:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PER', 'Pedido Realizado'), ('SES', 'Separa\xe7\xe3o em Estoque'), ('EMM', 'Em montagem R\xedgido'), ('RET', 'Realiza\xe7\xe3o de testes'), ('CDO', 'Conclu\xeddo')], default='PER', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('category', models.CharField(choices=[('PROC', 'Processadores'), ('RAM', 'Mem\xf3ria RAM'), ('HD', 'Disco R\xedgido'), ('VCD', 'Placa de V\xeddeo'), ('CAB', 'Gabinete'), ('MOT', 'Placa m\xe3e'), ('SRC', 'Fonte')], max_length=3)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('especification', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiproduct.Product')),
            ],
        ),
        migrations.AddField(
            model_name='demand',
            name='cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab_product', to='apiproduct.Product'),
        ),
        migrations.AddField(
            model_name='demand',
            name='hd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_product', to='apiproduct.Product'),
        ),
        migrations.AddField(
            model_name='demand',
            name='mot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mot_product', to='apiproduct.Product'),
        ),
        migrations.AddField(
            model_name='demand',
            name='proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proc_product', to='apiproduct.Product'),
        ),
        migrations.AddField(
            model_name='demand',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_product', to='apiproduct.Product'),
        ),
        migrations.AddField(
            model_name='demand',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_product', to='apiproduct.Product'),
        ),
        migrations.AddField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demand',
            name='vcd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcd_product', to='apiproduct.Product'),
        ),
    ]
